---
title: "Immersive Futures: Balancing Innovation and Ethics in Virtual Reality Development"
author: "Grace Sun"
date: "3/22/24"
output: pdf_document
fontsize: 12pt
---

Have you ever wanted to escape your reality? The ability to explore new worlds by just slipping on a headset is now widely accessible thanks to virtual reality (VR) technologies. With the global VR market projected to nearly triple in the next four years to over \$28 billion, VR is emerging as an undeniably important and rapidly growing field (Alsop, 2023). The “metaverse”, a term popularized by tech giant Meta for a complex virtual reality that doesn’t even exist yet, is projected to generate up to $5 trillion in value by 2030 according to leading consulting firm Mckinsey & Company (2022). The expansion of this field is driving researchers to work on the enhancement of the immersive experience of VR by studying software and hardware features of headsets and their relationships to user engagement. This paper examines the research methodologies, results, and ethical considerations presented in “Immersion Metrics for Virtual Reality” by Matias N. Selzer and Silvia M. Castro, in which the authors aim to develop a model for predicting VR immersion using over 20 different predictors. While their research focuses on a foundational approach to predicting immersion in virtual reality through a user study, it also raises significant ethical concerns about VR usage, including issues like data privacy, content regulation, and human connection to reality.

The methodology of this study, which is currently in its preprint state and awaiting peer review, proceeds in several stages, beginning with a detailed definition and categorization of various predictor variables to ensure the study’s clarity and reproducibility. After this foundational work, the researchers conducted a user study, which was centered around a 30 year old male participant who completed 401 successful trials. In these trials, the participant explored diverse virtual environments using the same VR headset but with varying settings for each session, followed by self-reporting his perceived level of immersion. This approach, where there is only one participant participating in a study, is known as single subject design, which significantly improves the consistency and comparability of trial outcomes. This is especially important in this trial, particularly because it relies on self-reported immersion values, which is a subjective measure that could differ from person to person. 
	
	
The study then moved on to the data analysis phase, where preliminary Kolmogorov-Smirnov tests indicated that the data did not conform to a normal distribution, leading to nonparametric tests being performed with a 95% confidence interval, followed by correlation tests. The research team proceeded to generate five direct models as a start to their efforts in identifying the most effective predictors of immersion. This initial exploration included simple linear models, complete models (both with and without interactions), and manually selected models based on significant variables. To further refine these models, feature selection techniques were used to evaluate the statistical significance of adding or removing variables. In this stage, the authors defined 4 groups with different p values and performed forward, backward, and stepwise regression, resulting in the generation of 12 additional models. In the final phase of the study, the researchers validated all of the constructed models using k-iteration cross-validation and carefully selected three final models based on their R^2 values and the number of included coefficients and predictors in each model. This thorough and detailed methodology highlights the authors’ efforts to develop robust and useful models to predict VR immersion.

In their study, the authors employed statistical correlation tests that revealed small positive correlations between immersion score and the variables of screen width, frames per second, and contrast. This suggests that enhancements in these areas could lead to more immersive VR experiences. Additionally, the presence of textures within virtual environments was positively correlated with increased immersion levels, illustrating that users feel more immersed when objects and environments appear to have realistic appearances. The study also found significant differences between audio output methods and locomotion techniques and their impact on immersion. Specifically, using headphones and walk-in place methods of sound and movement were associated with the highest levels of immersion, followed by speakers and joystick locomotion, with no sound and the use of teleportation associated with the lowest immersion scores. 
	
	
Through their analysis, the authors developed a range of models to quantify the relationship between various predictors and the overall VR immersion level, utilizing the coefficient of determination ($R^2$) as a benchmark for model effectiveness. After producing 17 total models (only 11 of which were unique) through the initial process of feature selection and validation, the authors ultimately chose three models based on their ability to balance predictive accuracy, computational efficiency, and the risk of overfitting, which is a concern with models that have a high number of coefficients and predictors. Model 1 was chosen for its high predictive accuracy, possessing an $R^2$ value of 0.5542, but its complexity, with 42 coefficients and 18 predictors, suggests a higher potential of overfitting. Conversely, Models 2 and 3, with 24 and 13 coefficients, and 15 and 9 predictors, respectively, are smaller and simpler models with $R^2$ values of 0.4691 and 0.4235. These models sacrifice some predictive power for better generalization and faster computation. Concluding their research, the authors applied all three of the final models to evaluating the immersive potential of three distinct VR headsets: Oculus Rift S, Oculus Quest, and Oculus Go. By analyzing the specific hardware and software attributes of each headset, they demonstrate a practical application of their models for manufacturers aiming to improve the immersive experience and design of their VR devices. 


The rapid expansion of virtual reality technology introduces numerous ethical concerns. A primary concern is the issue of data privacy, particularly concerning the potential for extensive surveillance and data collection without informed consent from users. The ability of wearable VR headsets to monitor users’ gaze, vocal tones, facial expressions, and other personal data presents significant issues surrounding the collection and protection of this sensitive information. Content regulation within these virtual environments also poses a challenge, with few rules and regulations in place about what virtual content is deemed appropriate and who should have the authority to make these decisions. By generating problematic environments or displaying altered real life events, VR has the potential to subtly influence user behavior without their awareness. It's important that the safety and well-being of users is protected when using these headsets through careful content regulations.
	
	
As VR environments become more immersive, the line between virtual environments and reality may blur, leading to digital worlds that could become indistinguishable from reality. Increasingly immersive VR headsets could create a myriad of negative impacts since they encourage more time spent in virtual realities, including desensitization towards real-world experiences and a diminishing of human connection to reality. If virtual experiences can be created in a way where they are able to deliver continuous pleasure without the unpredictability and hardships of real life, the allure of staying forever in these virtual worlds could become irresistible. This brings into question the ethical implications of a potential preference for virtual perfection over the nuanced ups and downs of living in the real world.


These ethical considerations align with the philosophical question posed by American philosopher Robert Nozick in his thought experiment about the experience machine. By asking whether individuals would choose to plug into a machine for the rest of their life if the machine could simulate any pleasurable experience that a mind could desire, Nozick challenges the hedonistic view that pleasure is the sole indicator of a fulfilling life ("The Experience Machine," n.d.). The experience machine can be viewed as an analogy to VR technology, and it prompts a deeper reflection on the value of authentic experiences and the elements of reality that make life meaningful. Addressing all of the aforementioned ethical concerns is essential as we move towards a future where virtual realities become a part of daily life.


Virtual reality will one day change the world as we know it, following a legacy left behind by all of the other technological advancements that now shape our everyday lives. The work by Selzer and Castro on VR immersion metrics provide valuable insights into the potential for enhancing virtual experiences, and the models developed in the paper for measuring immersion will serve as essential tools for companies creating VR headsets. However, as the developments in VR technology are celebrated, it is also important to navigate the accompanying ethical challenges, including concerns about data privacy and the increasingly blurring boundaries between virtual and physical worlds. It’s difficult to balance the rapid growth in innovative technologies with ethical responsibility, but it is an undeniably important consideration.

\newpage

References


Alsop, T. (2023, July 3). *Consumer and Enterprise VR Revenue Worldwide 2026*. Statista. https://www.statista.com/statistics/1221522/virtual-reality-market-size-worldwide/


McKinsey & Company. (2022, June 14). *Value creation in the metaverse*. McKinsey & Company. https://www.mckinsey.com/capabilities/growth-marketing-and-sales/our-insights/value-creation-in-the-metaverse 


Selzer, M. N., & Castro, S. M. (2022, June 15). *Immersion metrics for virtual reality*. arXiv.org. https://arxiv.org/abs/2206.07748 


*The Experience Machine*. Internet encyclopedia of philosophy. (n.d.). https://iep.utm.edu/experience-machine/ 